# Generated by Django 5.0.6 on 2024-06-09 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo3',
            old_name='User',
            new_name='user',
        ),
    ]
